### ISSUE TITLE
[Bug] slf4j api class files included in the shaded client jar

### ISSUE THREAD

**Issue by nodece** [streamnative/oxia-java#129]
I'm migrating the slf4j to 2.0.12 from 1.7.32 on the Apache Pulsar, I noticed the oxia-client shaded includes the slf4j package, and the maven-shaded-plugin cannot exclude the slf4j package from the oxia-client shaded jar:

<img width="471" alt="image" src="https://github.com/streamnative/oxia-java/assets/16235121/b6cab677-2062-44b2-8733-1151eac05429">

Could you remove the slf4j package from the shaded jar.

Apache Pulsar PR: https://github.com/apache/pulsar/pull/22391

/cc @lhotari @merlimat

**Comment by lhotari** [comment]
There's also another problem that the POM doesn't look right for the unshaded version: https://repo1.maven.org/maven2/io/streamnative/oxia/oxia-client/0.1.1/oxia-client-0.1.1.pom . It seems that the shaded library would need to be published as a different artifact to support having a separate POM for the shaded library and the unshaded library. At least that's how it is addressed in Pulsar pulsar-client (shaded) and pulsar-client-original (non-shaded).

**Comment by lhotari** [comment]
Another shading issue is that it seems to be shading the already shaded netty pulled in with grpc. This could be a problem in some cases since the native libraries aren't properly relocated.

**Comment by lhotari** [comment]
@nodece please rename the issue report. Something like "DO NOT include the slf4j package to the shaded jar" isn't a great title for an issue report. A better one would be "[Bug] slf4j api included in the shaded client jar".

**Comment by merlimat** [comment]
Good point, we can create a separate module to do the shading, instead of using the classifier.

Also, I think the only reason to use shaded jar in Pulsar was a conflict with gRPC. I was trying to downgrade gRPC here so that we can use same version as Pulsar and remove the need for shading.

**Comment by merlimat** [comment]
> When using the original, the oxia needs to match the pulsar netty. Is it correct?

Biggest problem is gRPC that has to match, across BK, Pulsar and now Oxia client

**Comment by nodece** [comment]
This issue has been fixed by oxia@0.1.6.
